# Generated by Django 5.0.7 on 2024-08-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_feedback_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Создать в')),
            ],
            options={
                'verbose_name': 'Подпишись',
                'verbose_name_plural': 'Подпишись',
                'db_table': 'subscrible',
            },
        ),
    ]
