# Generated by Django 5.0.7 on 2024-08-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(choices=[(1, 'Активно ищу работу'), (2, 'Работаю над проектом')], default=1),
        ),
    ]
