# Generated by Django 5.0.7 on 2024-07-27 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriyaProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('logo', models.ImageField(upload_to='category/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категория проекта',
                'verbose_name_plural': 'Категория проекта',
                'db_table': 'category_project',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название проекта')),
                ('contact', models.CharField(max_length=250, verbose_name='Контакт')),
                ('valuta', models.IntegerField(choices=[(1, 'Руб'), (2, 'Долл')], default=1, verbose_name='Валюта')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('skils', models.JSONField(verbose_name='Навыки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='project/', verbose_name='Изображение')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.categoriyaproject', verbose_name='Категория')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проект',
                'db_table': 'project',
            },
        ),
    ]
