# Generated by Django 5.0.7 on 2024-07-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skils',
            field=models.JSONField(blank=True, null=True, verbose_name='Навыки'),
        ),
    ]
