# Generated by Django 5.0.7 on 2024-07-28 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Рубрику')),
            ],
            options={
                'verbose_name': 'Рубрику',
                'verbose_name_plural': 'Рубрику',
                'db_table': 'heading',
            },
        ),
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=250, verbose_name='Контактная информация')),
                ('experience', models.IntegerField(verbose_name='Опыт работы')),
                ('hard_skills', models.JSONField(verbose_name='Hard skills')),
                ('soft_skills', models.JSONField(verbose_name='Soft Skills')),
                ('description', models.TextField(verbose_name='Описание')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.heading', verbose_name='Рубрику')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'db_table': 'resume_model',
            },
        ),
        migrations.CreateModel(
            name='FavoritesResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='resume.resumemodel')),
            ],
            options={
                'verbose_name': 'Избранно резюме',
                'verbose_name_plural': 'Избранно резюме',
                'db_table': 'favorites_resume',
            },
        ),
    ]
