# Generated by Django 5.0.7 on 2024-07-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='hard_skills',
            field=models.JSONField(blank=True, null=True, verbose_name='Hard skills'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='soft_skills',
            field=models.JSONField(blank=True, null=True, verbose_name='Soft Skills'),
        ),
    ]
