# Generated by Django 5.0.7 on 2024-08-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resumemodel_hard_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
